// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: wo-proto3-2594160131.tmp

package won

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WOReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wosrvs  string            `protobuf:"bytes,1,opt,name=wosrvs,proto3" json:"wosrvs,omitempty"`
	Wocmdid string            `protobuf:"bytes,2,opt,name=wocmdid,proto3" json:"wocmdid,omitempty"`
	Headers map[string]string `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Payload []byte            `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *WOReq) Reset() {
	*x = WOReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_2594160131_tmp_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOReq) ProtoMessage() {}

func (x *WOReq) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_2594160131_tmp_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOReq.ProtoReflect.Descriptor instead.
func (*WOReq) Descriptor() ([]byte, []int) {
	return file_wo_proto3_2594160131_tmp_rawDescGZIP(), []int{0}
}

func (x *WOReq) GetWosrvs() string {
	if x != nil {
		return x.Wosrvs
	}
	return ""
}

func (x *WOReq) GetWocmdid() string {
	if x != nil {
		return x.Wocmdid
	}
	return ""
}

func (x *WOReq) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WOReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WOResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wosrvs  string            `protobuf:"bytes,1,opt,name=wosrvs,proto3" json:"wosrvs,omitempty"`
	Wocmdid string            `protobuf:"bytes,2,opt,name=wocmdid,proto3" json:"wocmdid,omitempty"`
	Headers map[string]string `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Payload []byte            `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *WOResp) Reset() {
	*x = WOResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_2594160131_tmp_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOResp) ProtoMessage() {}

func (x *WOResp) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_2594160131_tmp_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOResp.ProtoReflect.Descriptor instead.
func (*WOResp) Descriptor() ([]byte, []int) {
	return file_wo_proto3_2594160131_tmp_rawDescGZIP(), []int{1}
}

func (x *WOResp) GetWosrvs() string {
	if x != nil {
		return x.Wosrvs
	}
	return ""
}

func (x *WOResp) GetWocmdid() string {
	if x != nil {
		return x.Wocmdid
	}
	return ""
}

func (x *WOResp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WOResp) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WOLivlinessProbe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WOLivlinessProbe) Reset() {
	*x = WOLivlinessProbe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_2594160131_tmp_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOLivlinessProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOLivlinessProbe) ProtoMessage() {}

func (x *WOLivlinessProbe) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_2594160131_tmp_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOLivlinessProbe.ProtoReflect.Descriptor instead.
func (*WOLivlinessProbe) Descriptor() ([]byte, []int) {
	return file_wo_proto3_2594160131_tmp_rawDescGZIP(), []int{2}
}

type WOLivlinessProbeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WOLivlinessProbeResult) Reset() {
	*x = WOLivlinessProbeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_2594160131_tmp_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOLivlinessProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOLivlinessProbeResult) ProtoMessage() {}

func (x *WOLivlinessProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_2594160131_tmp_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOLivlinessProbeResult.ProtoReflect.Descriptor instead.
func (*WOLivlinessProbeResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_2594160131_tmp_rawDescGZIP(), []int{3}
}

var File_wo_proto3_2594160131_tmp protoreflect.FileDescriptor

var file_wo_proto3_2594160131_tmp_rawDesc = []byte{
	0x0a, 0x18, 0x77, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x2d, 0x32, 0x35, 0x39, 0x34,
	0x31, 0x36, 0x30, 0x31, 0x33, 0x31, 0x2e, 0x74, 0x6d, 0x70, 0x12, 0x0b, 0x77, 0x6f, 0x70, 0x2e,
	0x77, 0x6f, 0x6e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x05, 0x57, 0x4f, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x6f, 0x73, 0x72, 0x76, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x77, 0x6f, 0x73, 0x72, 0x76, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f,
	0x63, 0x6d, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x63,
	0x6d, 0x64, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x77, 0x6f, 0x70, 0x2e, 0x77, 0x6f, 0x6e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x57, 0x4f, 0x52, 0x65, 0x71, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xcc, 0x01, 0x0a, 0x06, 0x57, 0x4f, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x77, 0x6f, 0x73, 0x72, 0x76, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x77, 0x6f, 0x73, 0x72, 0x76, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x63, 0x6d,
	0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x63, 0x6d, 0x64,
	0x69, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x77, 0x6f, 0x70, 0x2e, 0x77, 0x6f, 0x6e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x57, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x12, 0x0a, 0x10, 0x57, 0x4f, 0x4c, 0x69, 0x76, 0x6c, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x57, 0x4f, 0x4c, 0x69,
	0x76, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2f, 0x77, 0x6f, 0x70, 0x2f, 0x77, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wo_proto3_2594160131_tmp_rawDescOnce sync.Once
	file_wo_proto3_2594160131_tmp_rawDescData = file_wo_proto3_2594160131_tmp_rawDesc
)

func file_wo_proto3_2594160131_tmp_rawDescGZIP() []byte {
	file_wo_proto3_2594160131_tmp_rawDescOnce.Do(func() {
		file_wo_proto3_2594160131_tmp_rawDescData = protoimpl.X.CompressGZIP(file_wo_proto3_2594160131_tmp_rawDescData)
	})
	return file_wo_proto3_2594160131_tmp_rawDescData
}

var file_wo_proto3_2594160131_tmp_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wo_proto3_2594160131_tmp_goTypes = []interface{}{
	(*WOReq)(nil),                  // 0: wop.woncore.WOReq
	(*WOResp)(nil),                 // 1: wop.woncore.WOResp
	(*WOLivlinessProbe)(nil),       // 2: wop.woncore.WOLivlinessProbe
	(*WOLivlinessProbeResult)(nil), // 3: wop.woncore.WOLivlinessProbeResult
	nil,                            // 4: wop.woncore.WOReq.HeadersEntry
	nil,                            // 5: wop.woncore.WOResp.HeadersEntry
}
var file_wo_proto3_2594160131_tmp_depIdxs = []int32{
	4, // 0: wop.woncore.WOReq.headers:type_name -> wop.woncore.WOReq.HeadersEntry
	5, // 1: wop.woncore.WOResp.headers:type_name -> wop.woncore.WOResp.HeadersEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wo_proto3_2594160131_tmp_init() }
func file_wo_proto3_2594160131_tmp_init() {
	if File_wo_proto3_2594160131_tmp != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wo_proto3_2594160131_tmp_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_2594160131_tmp_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_2594160131_tmp_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOLivlinessProbe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_2594160131_tmp_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOLivlinessProbeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wo_proto3_2594160131_tmp_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wo_proto3_2594160131_tmp_goTypes,
		DependencyIndexes: file_wo_proto3_2594160131_tmp_depIdxs,
		MessageInfos:      file_wo_proto3_2594160131_tmp_msgTypes,
	}.Build()
	File_wo_proto3_2594160131_tmp = out.File
	file_wo_proto3_2594160131_tmp_rawDesc = nil
	file_wo_proto3_2594160131_tmp_goTypes = nil
	file_wo_proto3_2594160131_tmp_depIdxs = nil
}
