// Handlers code generated by wogen. Should not modify
package main

import (
	"context"
	"fmt"

	"github.com/workoak/wogo/cli"
	wogcli "github.com/workoak/wop/wog/cli"
)

func main() {
	app := NewCli()
	err := app.Run(context.Background())
	if err != nil {
		panic(err)
	}
}

func NewCli() *cli.Framework {
	app := &cli.Framework{}

	rootCmd := &cli.Command{
		Usage: "wogcli",
		Short: "wo generator",

		Version: "v0.1.3",
	}

	prepareGenerateCmd(rootCmd)
	prepareInitializeCmd(rootCmd)
	prepareValidateCmd(rootCmd)
	app.Root = rootCmd

	return app
}

func prepareGenerateCmd(rootCmd *cli.Command) {
	cmd := &wogcli.GenerateCmd{}
	cliCmd := &cli.Command{
		Usage: "generate",
		Short: "generate wop code from from wop schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := wogcli.RunGenerateCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	cliCmd.Flags().StringVar(&cmd.In, "in", "", "input wop spec file")
	cliCmd.Flags().StringVar(&cmd.Lang, "lang", "", "")
	cliCmd.Flags().StringVar(&cmd.Outdir, "outdir", "", "")
	rootCmd.AddCommand(cliCmd)

}
func prepareInitializeCmd(rootCmd *cli.Command) {
	cmd := &wogcli.InitializeCmd{}
	cliCmd := &cli.Command{
		Usage: "init",
		Short: "initalize a new wop schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := wogcli.RunInitializeCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	cliCmd.Flags().StringVar(&cmd.Name, "name", "", "")
	cliCmd.Flags().StringVar(&cmd.Namespace, "namespace", "", "")
	rootCmd.AddCommand(cliCmd)

}
func prepareValidateCmd(rootCmd *cli.Command) {
	cmd := &wogcli.ValidateCmd{}
	cliCmd := &cli.Command{
		Usage: "validate",
		Short: "validate wop spec",
		Run: func(ctx *cli.Context, args []string) {
			_, err := wogcli.RunValidateCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	cliCmd.Flags().StringVar(&cmd.In, "in", "", "input wop spec file")
	rootCmd.AddCommand(cliCmd)

}
