// Handlers code generated by mvgen. Should not modify
package main

import (
	"context"
	"fmt"

	mvgen "github.com/mainvec/mvep/mvgen/mvpapi"
	api "github.com/mainvec/mvep/mvgen/mvpapi/api"
	"github.com/mainvec/ugo/cli"
)

var commandRunner *api.PkgCommandRunner

func main() {
	commandRunner = mvgen.GetCommandRunner()
	app := NewCli()
	err := app.Run(context.Background())
	if err != nil {
		panic(err)
	}
}

func NewCli() *cli.Framework {
	app := &cli.Framework{}

	rootCmd := &cli.Command{
		Usage:   "mvgen",
		Short:   "mvgen tool",
		Long:    "mvgen is a tool to generate code from a mainvec schema",
		Version: MVGEN_VERSION,
	}

	prepareGenerateCmd(rootCmd)
	prepareInitializeCmd(rootCmd)
	prepareValidateCmd(rootCmd)
	app.Root = rootCmd

	return app
}

func prepareGenerateCmd(rootCmd *cli.Command) {
	cmd := &api.GenerateCmd{}
	cliCmd := &cli.Command{
		Usage: "generate",
		Short: "generate mvp code from from MVEP schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := commandRunner.RunGenerateCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	//using field alias: in
	cliCmd.Flags().StringVar(&cmd.In, "in", "", "input mvep spec file")
	//using field alias:
	cliCmd.Flags().StringVar(&cmd.Lang, "lang", "", "")
	//using field alias:
	cliCmd.Flags().StringVar(&cmd.Outdir, "outdir", "", "")
	//format parameter for serialization type
	cliCmd.Flags().StringVar(&cmd.Format, "format", "", "serialization format (plain=plain json, pb3=protobuf)")
	rootCmd.AddCommand(cliCmd)

}
func prepareInitializeCmd(rootCmd *cli.Command) {
	cmd := &api.InitializeCmd{}
	cliCmd := &cli.Command{
		Usage: "init",
		Short: "Initialize a new MVEP Schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := commandRunner.RunInitializeCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	//using field alias:
	cliCmd.Flags().StringVar(&cmd.Name, "name", "", "")
	//using field alias: ns
	cliCmd.Flags().StringVar(&cmd.Namespace, "ns", "", "")
	rootCmd.AddCommand(cliCmd)

}
func prepareValidateCmd(rootCmd *cli.Command) {
	cmd := &api.ValidateCmd{}
	cliCmd := &cli.Command{
		Usage: "validate",
		Short: "validate mvep spec",
		Run: func(ctx *cli.Context, args []string) {
			_, err := commandRunner.RunValidateCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	//using field alias: in
	cliCmd.Flags().StringVar(&cmd.In, "in", "", "input mvep spec file")
	rootCmd.AddCommand(cliCmd)

}
