// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: wo-proto3-3809627072.tmp

package wogcli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input  string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Outdir string `protobuf:"bytes,2,opt,name=outdir,proto3" json:"outdir,omitempty"`
	Lang   string `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
}

func (x *GenerateCmd) Reset() {
	*x = GenerateCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_3809627072_tmp_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCmd) ProtoMessage() {}

func (x *GenerateCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_3809627072_tmp_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCmd.ProtoReflect.Descriptor instead.
func (*GenerateCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_3809627072_tmp_rawDescGZIP(), []int{0}
}

func (x *GenerateCmd) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *GenerateCmd) GetOutdir() string {
	if x != nil {
		return x.Outdir
	}
	return ""
}

func (x *GenerateCmd) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type GenerateCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateCmdResult) Reset() {
	*x = GenerateCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_3809627072_tmp_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCmdResult) ProtoMessage() {}

func (x *GenerateCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_3809627072_tmp_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCmdResult.ProtoReflect.Descriptor instead.
func (*GenerateCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_3809627072_tmp_rawDescGZIP(), []int{1}
}

type InitializeCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *InitializeCmd) Reset() {
	*x = InitializeCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_3809627072_tmp_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeCmd) ProtoMessage() {}

func (x *InitializeCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_3809627072_tmp_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeCmd.ProtoReflect.Descriptor instead.
func (*InitializeCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_3809627072_tmp_rawDescGZIP(), []int{2}
}

func (x *InitializeCmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitializeCmd) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type InitializeCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitializeCmdResult) Reset() {
	*x = InitializeCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_3809627072_tmp_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeCmdResult) ProtoMessage() {}

func (x *InitializeCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_3809627072_tmp_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeCmdResult.ProtoReflect.Descriptor instead.
func (*InitializeCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_3809627072_tmp_rawDescGZIP(), []int{3}
}

var File_wo_proto3_3809627072_tmp protoreflect.FileDescriptor

var file_wo_proto3_3809627072_tmp_rawDesc = []byte{
	0x0a, 0x18, 0x77, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x2d, 0x33, 0x38, 0x30, 0x39,
	0x36, 0x32, 0x37, 0x30, 0x37, 0x32, 0x2e, 0x74, 0x6d, 0x70, 0x12, 0x0a, 0x77, 0x6f, 0x67, 0x2e,
	0x77, 0x6f, 0x67, 0x63, 0x6c, 0x69, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x75, 0x74, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75,
	0x74, 0x64, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x41, 0x0a,
	0x0d, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0x15, 0x0a, 0x13, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x43, 0x6d,
	0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2f, 0x77, 0x6f,
	0x70, 0x2f, 0x77, 0x6f, 0x67, 0x3b, 0x77, 0x6f, 0x67, 0x63, 0x6c, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wo_proto3_3809627072_tmp_rawDescOnce sync.Once
	file_wo_proto3_3809627072_tmp_rawDescData = file_wo_proto3_3809627072_tmp_rawDesc
)

func file_wo_proto3_3809627072_tmp_rawDescGZIP() []byte {
	file_wo_proto3_3809627072_tmp_rawDescOnce.Do(func() {
		file_wo_proto3_3809627072_tmp_rawDescData = protoimpl.X.CompressGZIP(file_wo_proto3_3809627072_tmp_rawDescData)
	})
	return file_wo_proto3_3809627072_tmp_rawDescData
}

var file_wo_proto3_3809627072_tmp_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wo_proto3_3809627072_tmp_goTypes = []interface{}{
	(*GenerateCmd)(nil),         // 0: wog.wogcli.GenerateCmd
	(*GenerateCmdResult)(nil),   // 1: wog.wogcli.GenerateCmdResult
	(*InitializeCmd)(nil),       // 2: wog.wogcli.InitializeCmd
	(*InitializeCmdResult)(nil), // 3: wog.wogcli.InitializeCmdResult
}
var file_wo_proto3_3809627072_tmp_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wo_proto3_3809627072_tmp_init() }
func file_wo_proto3_3809627072_tmp_init() {
	if File_wo_proto3_3809627072_tmp != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wo_proto3_3809627072_tmp_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_3809627072_tmp_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_3809627072_tmp_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_3809627072_tmp_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wo_proto3_3809627072_tmp_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wo_proto3_3809627072_tmp_goTypes,
		DependencyIndexes: file_wo_proto3_3809627072_tmp_depIdxs,
		MessageInfos:      file_wo_proto3_3809627072_tmp_msgTypes,
	}.Build()
	File_wo_proto3_3809627072_tmp = out.File
	file_wo_proto3_3809627072_tmp_rawDesc = nil
	file_wo_proto3_3809627072_tmp_goTypes = nil
	file_wo_proto3_3809627072_tmp_depIdxs = nil
}
