// Handlers code generated by wogen. Should not modify 
package wogcli

import (
	"context"
)

 
type GenerateCmdHandler func(context.Context, *GenerateCmd) (*GenerateCmdResult, error) 
type InitializeCmdHandler func(context.Context, *InitializeCmd) (*InitializeCmdResult, error) 
type ValidateCmdHandler func(context.Context, *ValidateCmd) (*ValidateCmdResult, error)
