// Code generated by toolkit. DO NOT EDIT.
// Plain Go structs with JSON tags (plain format - no protobuf dependency)
package api


// GenerateCmd is a command request
type GenerateCmd struct {
	In string `json:"in,omitempty" cbor:"in,omitempty" mvp:"1,in"`
	Outdir string `json:"outdir,omitempty" cbor:"outdir,omitempty" mvp:"2,outdir"`
	Lang string `json:"lang,omitempty" cbor:"lang,omitempty" mvp:"3,lang"`
	Format string `json:"format,omitempty" cbor:"format,omitempty" mvp:"4,format"`
}

// GetIn returns the in field value
func (x *GenerateCmd) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

// SetIn sets the in field value
func (x *GenerateCmd) SetIn(v string) {
	x.In = v
}

// GetOutdir returns the outdir field value
func (x *GenerateCmd) GetOutdir() string {
	if x != nil {
		return x.Outdir
	}
	return ""
}

// SetOutdir sets the outdir field value
func (x *GenerateCmd) SetOutdir(v string) {
	x.Outdir = v
}

// GetLang returns the lang field value
func (x *GenerateCmd) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// SetLang sets the lang field value
func (x *GenerateCmd) SetLang(v string) {
	x.Lang = v
}

// GetFormat returns the format field value
func (x *GenerateCmd) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// SetFormat sets the format field value
func (x *GenerateCmd) SetFormat(v string) {
	x.Format = v
}

// GenerateCmdResult is the response for GenerateCmd
type GenerateCmdResult struct {
}

// InitializeCmd is a command request
type InitializeCmd struct {
	Name string `json:"name,omitempty" cbor:"name,omitempty" mvp:"1,name"`
	Namespace string `json:"namespace,omitempty" cbor:"namespace,omitempty" mvp:"2,namespace"`
}

// GetName returns the name field value
func (x *InitializeCmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SetName sets the name field value
func (x *InitializeCmd) SetName(v string) {
	x.Name = v
}

// GetNamespace returns the namespace field value
func (x *InitializeCmd) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// SetNamespace sets the namespace field value
func (x *InitializeCmd) SetNamespace(v string) {
	x.Namespace = v
}

// InitializeCmdResult is the response for InitializeCmd
type InitializeCmdResult struct {
}

// ValidateCmd is a command request
type ValidateCmd struct {
	In string `json:"in,omitempty" cbor:"in,omitempty" mvp:"1,in"`
}

// GetIn returns the in field value
func (x *ValidateCmd) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

// SetIn sets the in field value
func (x *ValidateCmd) SetIn(v string) {
	x.In = v
}

// ValidateCmdResult is the response for ValidateCmd
type ValidateCmdResult struct {
	Valid bool `json:"valid,omitempty" cbor:"valid,omitempty" mvp:"1,valid"`
	Errors []string `json:"errors,omitempty" cbor:"errors,omitempty" mvp:"5,errors"`
	Warnings []string `json:"warnings,omitempty" cbor:"warnings,omitempty" mvp:"10,warnings"`
}

// GetValid returns the valid field value
func (x *ValidateCmdResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// SetValid sets the valid field value
func (x *ValidateCmdResult) SetValid(v bool) {
	x.Valid = v
}

// GetErrors returns the errors field value
func (x *ValidateCmdResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// SetErrors sets the errors field value
func (x *ValidateCmdResult) SetErrors(v []string) {
	x.Errors = v
}

// GetWarnings returns the warnings field value
func (x *ValidateCmdResult) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// SetWarnings sets the warnings field value
func (x *ValidateCmdResult) SetWarnings(v []string) {
	x.Warnings = v
}
