// NOMVGEN
// Default implementation generated by mvgen.
// Can be modifid but might be re-genrated by mvgen, if allowed to
package mvgen

import (
	"context"
	"fmt"
	"os"

	"github.com/mainvec/mvep/mvgen"
	api "github.com/mainvec/mvep/mvgen/mvpapi/api"
)

func runGenerateCmd(ctx context.Context, cmd *api.GenerateCmd) (*api.GenerateCmdResult, error) {
	err := mvgen.ExecuteGenerate(ctx, cmd.In, cmd.Outdir, cmd.Lang, false, cmd.Format)
	if err != nil {
		return nil, err
	}
	return &api.GenerateCmdResult{}, nil
}

func runInitializeCmd(ctx context.Context, cmd *api.InitializeCmd) (*api.InitializeCmdResult, error) {
	err := mvgen.ExeucuteInitializeCmd(ctx, cmd.Name, cmd.Namespace)
	if err != nil {
		return nil, err
	}
	return &api.InitializeCmdResult{}, nil
}

func runValidateCmd(ctx context.Context, cmd *api.ValidateCmd) (*api.ValidateCmdResult, error) {
	res, err := mvgen.ExecuteValidateCmd(ctx, cmd.In)
	if err != nil {
		return nil, err
	}
	cmdResult := &api.ValidateCmdResult{}
	cmdResult.Valid = res.Valid()
	if !res.Valid() {
		errs := make([]string, len(res.ValidationErrors()))
		for _, e := range res.ValidationErrors() {
			errs = append(errs, e.String())
		}
		cmdResult.Errors = errs
		fmt.Fprintf(os.Stderr, "MVEP Spec is InValid: %v\n", errs)
	} else {
		fmt.Printf("valid!.\n")
	}
	return cmdResult, nil
}
