// Handlers code generated by wogen. Should not modify
package main

import (
	"context"
	"fmt"

	wogcli "github.com/workoak/wop/wog/cli"
	"github.com/workoak/woutil/cli"
)

func main() {
	app := NewCli()
	err := app.Run(context.Background())
	if err != nil {
		panic(err)
	}
}

func NewCli() *cli.Framework {
	app := &cli.Framework{}

	rootCmd := &cli.Command{
		Usage: "wogcli",
		Short: "wo generator",

		Version: "v0.1",
	}

	prepareGenerateCmd(rootCmd)
	prepareInitializeCmd(rootCmd)
	prepareValidateCmd(rootCmd)
	app.Root = rootCmd

	return app
}

func prepareGenerateCmd(rootCmd *cli.Command) {
	cmd := &wogcli.GenerateCmd{}
	cliCmd := &cli.Command{
		Usage: "generate",
		Short: "initalize a new wop schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := wogcli.RunGenerateCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	cliCmd.Flags().StringVar(&cmd.In, "in", "", "input wop spec file")
	cliCmd.Flags().StringVar(&cmd.Lang, "lang", "", "")
	cliCmd.Flags().StringVar(&cmd.Outdir, "outdir", "", "")
	rootCmd.AddCommand(cliCmd)

}
func prepareInitializeCmd(rootCmd *cli.Command) {
	cmd := &wogcli.InitializeCmd{}
	cliCmd := &cli.Command{
		Usage: "init",
		Short: "initalize a new wop schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := wogcli.RunInitializeCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	cliCmd.Flags().StringVar(&cmd.Name, "name", "", "")
	cliCmd.Flags().StringVar(&cmd.Namespace, "namespace", "", "")
	rootCmd.AddCommand(cliCmd)

}
func prepareValidateCmd(rootCmd *cli.Command) {
	cmd := &wogcli.ValidateCmd{}
	cliCmd := &cli.Command{
		Usage: "validate",
		Short: "initalize a new wop schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := wogcli.RunValidateCmd(ctx, cmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}
	//Command Flags

	cliCmd.Flags().StringVar(&cmd.In, "in", "", "input wop spec file")
	rootCmd.AddCommand(cliCmd)

}

/*
func prepareInitCmd(rootCmd *cli.Command) {
	initCmd := &wogcli.InitializeCmd{}

	initCli := &cli.Command{
		Usage: "init",
		Short: "initalize a new wop schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := wogcli.RunInitCmd(ctx, initCmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}

	initCli.Flags().StringVar(&initCmd.Name, "name", "", "name of the wop schema")
	initCli.Flags().StringVar(&initCmd.Name, "namespace", "", "namespace of the wop schema")
	rootCmd.AddCommand(initCli)
}

func prepareGenerateCmd(rootCmd *cli.Command) {
	generateCmd := &wogcli.GenerateCmd{}
	generateCli := &cli.Command{
		Usage: "generate",
		Short: "generate code artifacts based on wop schema",
		Run: func(ctx *cli.Context, args []string) {
			_, err := wogcli.RunGenerateCmd(ctx, generateCmd)
			if err != nil {
				fmt.Fprintln(ctx.Errout(), err)

			}
		},
	}

	generateCli.Flags().StringVar(&generateCmd.Input, "in", "", "input wop schema file")
	generateCli.Flags().StringVar(&generateCmd.Lang, "lang", "", "language to generate code artifacts. e.g. go")
	generateCli.Flags().StringVar(&generateCmd.Outdir, "outdir", "", "output directory for generated code artifacts")

	rootCmd.AddCommand(generateCli)

}
*/
