// Handlers code generated by toolkit. Should not modify
package api

import (
	"context"
	"errors"
	"github.com/mainvec/mvep/runtime/go/mvep"
)

var _ mvep.Package = &mvepPackage{}
var _ mvep.CommandRunner = &PkgCommandRunner{}

type GenerateCmdHandler func(context.Context, *GenerateCmd) (*GenerateCmdResult, error)
type InitializeCmdHandler func(context.Context, *InitializeCmd) (*InitializeCmdResult, error)
type ValidateCmdHandler func(context.Context, *ValidateCmd) (*ValidateCmdResult, error)

type mvepPackage struct {
}

func NewPackage() mvep.Package {
	return &mvepPackage{}
}

type PkgCommandRunner struct {
	RunGenerateCmd   GenerateCmdHandler
	RunInitializeCmd InitializeCmdHandler
	RunValidateCmd   ValidateCmdHandler
}

func (p *mvepPackage) GetName() string {
	return "mvepPackage"
}

func (p *mvepPackage) InstanceOf(compName string) (any, bool) {
	return InstanceOf(compName)
}

func (p *mvepPackage) NameOf(comp any) string {
	return NameOf(comp)
}

func NewCommandRunner() *PkgCommandRunner {
	return &PkgCommandRunner{}
}
func (r *PkgCommandRunner) RunCmd(ctx context.Context, cmd any) (any, error) {
	switch cmd := cmd.(type) {

	case *GenerateCmd:
		return r.RunGenerateCmd(ctx, cmd)
	case *InitializeCmd:
		return r.RunInitializeCmd(ctx, cmd)
	case *ValidateCmd:
		return r.RunValidateCmd(ctx, cmd)
	default:
		return nil, errors.New("invalid command")
	}
}

func InstanceOf(compName string) (any, bool) {
	switch compName {

	case "GenerateCmd":
		return &GenerateCmd{}, true
	case "GenerateCmdResult":
		return &GenerateCmdResult{}, true
	case "InitializeCmd":
		return &InitializeCmd{}, true
	case "InitializeCmdResult":
		return &InitializeCmdResult{}, true
	case "ValidateCmd":
		return &ValidateCmd{}, true
	case "ValidateCmdResult":
		return &ValidateCmdResult{}, true
	default:
		return nil, false
	}
}

func NameOf(comp any) string {
	switch comp.(type) {

	case *GenerateCmd:
		return "GenerateCmd"
	case *GenerateCmdResult:
		return "GenerateCmdResult"
	case *InitializeCmd:
		return "InitializeCmd"
	case *InitializeCmdResult:
		return "InitializeCmdResult"
	case *ValidateCmd:
		return "ValidateCmd"
	case *ValidateCmdResult:
		return "ValidateCmdResult"
	default:
		return ""
	}
}
