// Handlers code generated by wogen. Should not modify
package api

import (
	"context"
	"errors"

	"github.com/mainvec/mvp/mvpgo/mvp"
)

var _ mvp.Package = &iunetPackage{}
var _ mvp.CommandRunner = &PkgCommandRunner{}

type BrokerCreateCmdHandler func(context.Context, *BrokerCreateCmd) (*BrokerCreateCmdResult, error)
type BrokerListCmdHandler func(context.Context, *BrokerListCmd) (*BrokerListCmdResult, error)
type ClientletCreateCmdHandler func(context.Context, *ClientletCreateCmd) (*ClientletCreateCmdResult, error)
type ClientletOpCmdHandler func(context.Context, *ClientletOpCmd) (*ClientletOpCmdResult, error)
type ConnectCmdHandler func(context.Context, *ConnectCmd) (*ConnectCmdResult, error)
type ExposeCmdHandler func(context.Context, *ExposeCmd) (*ExposeCmdResult, error)
type HubCreateCmdHandler func(context.Context, *HubCreateCmd) (*HubCreateCmdResult, error)
type HubListCmdHandler func(context.Context, *HubListCmd) (*HubListCmdResult, error)
type ServerletCreateCmdHandler func(context.Context, *ServerletCreateCmd) (*ServerletCreateCmdResult, error)
type ServerletOpCmdHandler func(context.Context, *ServerletOpCmd) (*ServerletOpCmdResult, error)

type iunetPackage struct {
}

func NewPackage() mvp.Package {
	return &iunetPackage{}
}

type PkgCommandRunner struct {
	RunBrokerCreateCmd    BrokerCreateCmdHandler
	RunBrokerListCmd      BrokerListCmdHandler
	RunClientletCreateCmd ClientletCreateCmdHandler
	RunClientletOpCmd     ClientletOpCmdHandler
	RunConnectCmd         ConnectCmdHandler
	RunExposeCmd          ExposeCmdHandler
	RunHubCreateCmd       HubCreateCmdHandler
	RunHubListCmd         HubListCmdHandler
	RunServerletCreateCmd ServerletCreateCmdHandler
	RunServerletOpCmd     ServerletOpCmdHandler
}

func (p *iunetPackage) GetName() string {
	return "iunetPackage"
}

func (p *iunetPackage) InstanceOf(compName string) (any, bool) {
	return InstanceOf(compName)
}

func (p *iunetPackage) NameOf(comp any) string {
	return NameOf(comp)
}

func NewCommandRunner() *PkgCommandRunner {
	return &PkgCommandRunner{}
}
func (r *PkgCommandRunner) RunCmd(ctx context.Context, cmd any) (any, error) {
	switch cmd := cmd.(type) {

	case *BrokerCreateCmd:
		return r.RunBrokerCreateCmd(ctx, cmd)
	case *BrokerListCmd:
		return r.RunBrokerListCmd(ctx, cmd)
	case *ClientletCreateCmd:
		return r.RunClientletCreateCmd(ctx, cmd)
	case *ClientletOpCmd:
		return r.RunClientletOpCmd(ctx, cmd)
	case *ConnectCmd:
		return r.RunConnectCmd(ctx, cmd)
	case *ExposeCmd:
		return r.RunExposeCmd(ctx, cmd)
	case *HubCreateCmd:
		return r.RunHubCreateCmd(ctx, cmd)
	case *HubListCmd:
		return r.RunHubListCmd(ctx, cmd)
	case *ServerletCreateCmd:
		return r.RunServerletCreateCmd(ctx, cmd)
	case *ServerletOpCmd:
		return r.RunServerletOpCmd(ctx, cmd)
	default:
		return nil, errors.New("invalid command")
	}
}

func InstanceOf(compName string) (any, bool) {
	switch compName {

	case "BrokerCreateCmd":
		return &BrokerCreateCmd{}, true
	case "BrokerCreateCmdResult":
		return &BrokerCreateCmdResult{}, true
	case "BrokerListCmd":
		return &BrokerListCmd{}, true
	case "BrokerListCmdResult":
		return &BrokerListCmdResult{}, true
	case "ClientletCreateCmd":
		return &ClientletCreateCmd{}, true
	case "ClientletCreateCmdResult":
		return &ClientletCreateCmdResult{}, true
	case "ClientletOpCmd":
		return &ClientletOpCmd{}, true
	case "ClientletOpCmdResult":
		return &ClientletOpCmdResult{}, true
	case "ConnectCmd":
		return &ConnectCmd{}, true
	case "ConnectCmdResult":
		return &ConnectCmdResult{}, true
	case "ExposeCmd":
		return &ExposeCmd{}, true
	case "ExposeCmdResult":
		return &ExposeCmdResult{}, true
	case "HubCreateCmd":
		return &HubCreateCmd{}, true
	case "HubCreateCmdResult":
		return &HubCreateCmdResult{}, true
	case "HubListCmd":
		return &HubListCmd{}, true
	case "HubListCmdResult":
		return &HubListCmdResult{}, true
	case "ServerletCreateCmd":
		return &ServerletCreateCmd{}, true
	case "ServerletCreateCmdResult":
		return &ServerletCreateCmdResult{}, true
	case "ServerletOpCmd":
		return &ServerletOpCmd{}, true
	case "ServerletOpCmdResult":
		return &ServerletOpCmdResult{}, true
	default:
		return nil, false
	}
}

func NameOf(comp any) string {
	switch comp.(type) {

	case *BrokerCreateCmd:
		return "BrokerCreateCmd"
	case *BrokerCreateCmdResult:
		return "BrokerCreateCmdResult"
	case *BrokerListCmd:
		return "BrokerListCmd"
	case *BrokerListCmdResult:
		return "BrokerListCmdResult"
	case *ClientletCreateCmd:
		return "ClientletCreateCmd"
	case *ClientletCreateCmdResult:
		return "ClientletCreateCmdResult"
	case *ClientletOpCmd:
		return "ClientletOpCmd"
	case *ClientletOpCmdResult:
		return "ClientletOpCmdResult"
	case *ConnectCmd:
		return "ConnectCmd"
	case *ConnectCmdResult:
		return "ConnectCmdResult"
	case *ExposeCmd:
		return "ExposeCmd"
	case *ExposeCmdResult:
		return "ExposeCmdResult"
	case *HubCreateCmd:
		return "HubCreateCmd"
	case *HubCreateCmdResult:
		return "HubCreateCmdResult"
	case *HubListCmd:
		return "HubListCmd"
	case *HubListCmdResult:
		return "HubListCmdResult"
	case *ServerletCreateCmd:
		return "ServerletCreateCmd"
	case *ServerletCreateCmdResult:
		return "ServerletCreateCmdResult"
	case *ServerletOpCmd:
		return "ServerletOpCmd"
	case *ServerletOpCmdResult:
		return "ServerletOpCmdResult"
	default:
		return ""
	}
}
