// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.28.3
// source: wo-proto3-22483931.tmp

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Serverlet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid             string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	HubUUID          string `protobuf:"bytes,3,opt,name=hubUUID,proto3" json:"hubUUID,omitempty"`
	Desc             string `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Port             int32  `protobuf:"varint,10,opt,name=port,proto3" json:"port,omitempty"`
	ServerletAddress string `protobuf:"bytes,12,opt,name=serverletAddress,proto3" json:"serverletAddress,omitempty"`
	Disabled         bool   `protobuf:"varint,14,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ManualStartup    bool   `protobuf:"varint,15,opt,name=manualStartup,proto3" json:"manualStartup,omitempty"`
	ConnState        int32  `protobuf:"varint,16,opt,name=connState,proto3" json:"connState,omitempty"`
}

func (x *Serverlet) Reset() {
	*x = Serverlet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Serverlet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Serverlet) ProtoMessage() {}

func (x *Serverlet) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Serverlet.ProtoReflect.Descriptor instead.
func (*Serverlet) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{0}
}

func (x *Serverlet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Serverlet) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Serverlet) GetHubUUID() string {
	if x != nil {
		return x.HubUUID
	}
	return ""
}

func (x *Serverlet) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Serverlet) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Serverlet) GetServerletAddress() string {
	if x != nil {
		return x.ServerletAddress
	}
	return ""
}

func (x *Serverlet) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Serverlet) GetManualStartup() bool {
	if x != nil {
		return x.ManualStartup
	}
	return false
}

func (x *Serverlet) GetConnState() int32 {
	if x != nil {
		return x.ConnState
	}
	return 0
}

type Clientlet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid             string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	HubUUID          string `protobuf:"bytes,3,opt,name=hubUUID,proto3" json:"hubUUID,omitempty"`
	ListeningAddr    string `protobuf:"bytes,5,opt,name=listeningAddr,proto3" json:"listeningAddr,omitempty"`
	Desc             string `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	ServerletAddress string `protobuf:"bytes,10,opt,name=serverletAddress,proto3" json:"serverletAddress,omitempty"`
	ClientletPort    int32  `protobuf:"varint,12,opt,name=clientletPort,proto3" json:"clientletPort,omitempty"`
	Disabled         bool   `protobuf:"varint,14,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ManualStartup    bool   `protobuf:"varint,15,opt,name=manualStartup,proto3" json:"manualStartup,omitempty"`
	ConnState        int32  `protobuf:"varint,16,opt,name=connState,proto3" json:"connState,omitempty"`
}

func (x *Clientlet) Reset() {
	*x = Clientlet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clientlet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clientlet) ProtoMessage() {}

func (x *Clientlet) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clientlet.ProtoReflect.Descriptor instead.
func (*Clientlet) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{1}
}

func (x *Clientlet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Clientlet) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Clientlet) GetHubUUID() string {
	if x != nil {
		return x.HubUUID
	}
	return ""
}

func (x *Clientlet) GetListeningAddr() string {
	if x != nil {
		return x.ListeningAddr
	}
	return ""
}

func (x *Clientlet) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Clientlet) GetServerletAddress() string {
	if x != nil {
		return x.ServerletAddress
	}
	return ""
}

func (x *Clientlet) GetClientletPort() int32 {
	if x != nil {
		return x.ClientletPort
	}
	return 0
}

func (x *Clientlet) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Clientlet) GetManualStartup() bool {
	if x != nil {
		return x.ManualStartup
	}
	return false
}

func (x *Clientlet) GetConnState() int32 {
	if x != nil {
		return x.ConnState
	}
	return 0
}

type Hub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string       `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Desc          string       `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Serverlets    []*Serverlet `protobuf:"bytes,10,rep,name=serverlets,proto3" json:"serverlets,omitempty"`
	Clientlets    []*Clientlet `protobuf:"bytes,11,rep,name=clientlets,proto3" json:"clientlets,omitempty"`
	Disabled      bool         `protobuf:"varint,14,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ManualStartup bool         `protobuf:"varint,15,opt,name=manualStartup,proto3" json:"manualStartup,omitempty"`
}

func (x *Hub) Reset() {
	*x = Hub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hub) ProtoMessage() {}

func (x *Hub) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hub.ProtoReflect.Descriptor instead.
func (*Hub) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{2}
}

func (x *Hub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hub) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Hub) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Hub) GetServerlets() []*Serverlet {
	if x != nil {
		return x.Serverlets
	}
	return nil
}

func (x *Hub) GetClientlets() []*Clientlet {
	if x != nil {
		return x.Clientlets
	}
	return nil
}

func (x *Hub) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Hub) GetManualStartup() bool {
	if x != nil {
		return x.ManualStartup
	}
	return false
}

type Broker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid       string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Desc       string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ConnParams string `protobuf:"bytes,6,opt,name=connParams,proto3" json:"connParams,omitempty"`
	AuthParams string `protobuf:"bytes,8,opt,name=authParams,proto3" json:"authParams,omitempty"`
	Disabled   bool   `protobuf:"varint,10,opt,name=disabled,proto3" json:"disabled,omitempty"`
}

func (x *Broker) Reset() {
	*x = Broker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Broker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broker) ProtoMessage() {}

func (x *Broker) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broker.ProtoReflect.Descriptor instead.
func (*Broker) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{3}
}

func (x *Broker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Broker) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Broker) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Broker) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Broker) GetConnParams() string {
	if x != nil {
		return x.ConnParams
	}
	return ""
}

func (x *Broker) GetAuthParams() string {
	if x != nil {
		return x.AuthParams
	}
	return ""
}

func (x *Broker) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type OperationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode string            `protobuf:"bytes,3,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Details    string            `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	Additional map[string]string `protobuf:"bytes,10,rep,name=additional,proto3" json:"additional,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{4}
}

func (x *OperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResult) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *OperationResult) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *OperationResult) GetAdditional() map[string]string {
	if x != nil {
		return x.Additional
	}
	return nil
}

type BrokerCreateCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc       string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ConnParams string `protobuf:"bytes,6,opt,name=connParams,proto3" json:"connParams,omitempty"`
	AuthParams string `protobuf:"bytes,8,opt,name=authParams,proto3" json:"authParams,omitempty"`
	Persist    bool   `protobuf:"varint,10,opt,name=persist,proto3" json:"persist,omitempty"`
	Skiptest   bool   `protobuf:"varint,11,opt,name=skiptest,proto3" json:"skiptest,omitempty"`
	Disabled   bool   `protobuf:"varint,12,opt,name=disabled,proto3" json:"disabled,omitempty"`
}

func (x *BrokerCreateCmd) Reset() {
	*x = BrokerCreateCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerCreateCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerCreateCmd) ProtoMessage() {}

func (x *BrokerCreateCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerCreateCmd.ProtoReflect.Descriptor instead.
func (*BrokerCreateCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{5}
}

func (x *BrokerCreateCmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrokerCreateCmd) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *BrokerCreateCmd) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BrokerCreateCmd) GetConnParams() string {
	if x != nil {
		return x.ConnParams
	}
	return ""
}

func (x *BrokerCreateCmd) GetAuthParams() string {
	if x != nil {
		return x.AuthParams
	}
	return ""
}

func (x *BrokerCreateCmd) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *BrokerCreateCmd) GetSkiptest() bool {
	if x != nil {
		return x.Skiptest
	}
	return false
}

func (x *BrokerCreateCmd) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type BrokerCreateCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Broker *Broker `protobuf:"bytes,1,opt,name=broker,proto3" json:"broker,omitempty"`
}

func (x *BrokerCreateCmdResult) Reset() {
	*x = BrokerCreateCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerCreateCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerCreateCmdResult) ProtoMessage() {}

func (x *BrokerCreateCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerCreateCmdResult.ProtoReflect.Descriptor instead.
func (*BrokerCreateCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{6}
}

func (x *BrokerCreateCmdResult) GetBroker() *Broker {
	if x != nil {
		return x.Broker
	}
	return nil
}

type BrokerListCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *BrokerListCmd) Reset() {
	*x = BrokerListCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerListCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerListCmd) ProtoMessage() {}

func (x *BrokerListCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerListCmd.ProtoReflect.Descriptor instead.
func (*BrokerListCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{7}
}

func (x *BrokerListCmd) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type BrokerListCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brokers []*Broker `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
}

func (x *BrokerListCmdResult) Reset() {
	*x = BrokerListCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerListCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerListCmdResult) ProtoMessage() {}

func (x *BrokerListCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerListCmdResult.ProtoReflect.Descriptor instead.
func (*BrokerListCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{8}
}

func (x *BrokerListCmdResult) GetBrokers() []*Broker {
	if x != nil {
		return x.Brokers
	}
	return nil
}

type ClientletCreateCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServerletAddress string `protobuf:"bytes,2,opt,name=serverletAddress,proto3" json:"serverletAddress,omitempty"`
	HubUUID          string `protobuf:"bytes,3,opt,name=hubUUID,proto3" json:"hubUUID,omitempty"`
	Broker           string `protobuf:"bytes,5,opt,name=broker,proto3" json:"broker,omitempty"`
	Port             int32  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Persist          bool   `protobuf:"varint,7,opt,name=persist,proto3" json:"persist,omitempty"`
	BrokerUUID       string `protobuf:"bytes,8,opt,name=brokerUUID,proto3" json:"brokerUUID,omitempty"`
	Disabled         bool   `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ManualStartup    bool   `protobuf:"varint,10,opt,name=manualStartup,proto3" json:"manualStartup,omitempty"`
	Desc             string `protobuf:"bytes,12,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *ClientletCreateCmd) Reset() {
	*x = ClientletCreateCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientletCreateCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientletCreateCmd) ProtoMessage() {}

func (x *ClientletCreateCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientletCreateCmd.ProtoReflect.Descriptor instead.
func (*ClientletCreateCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{9}
}

func (x *ClientletCreateCmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientletCreateCmd) GetServerletAddress() string {
	if x != nil {
		return x.ServerletAddress
	}
	return ""
}

func (x *ClientletCreateCmd) GetHubUUID() string {
	if x != nil {
		return x.HubUUID
	}
	return ""
}

func (x *ClientletCreateCmd) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *ClientletCreateCmd) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClientletCreateCmd) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *ClientletCreateCmd) GetBrokerUUID() string {
	if x != nil {
		return x.BrokerUUID
	}
	return ""
}

func (x *ClientletCreateCmd) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ClientletCreateCmd) GetManualStartup() bool {
	if x != nil {
		return x.ManualStartup
	}
	return false
}

func (x *ClientletCreateCmd) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ClientletCreateCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientlet *Clientlet `protobuf:"bytes,1,opt,name=clientlet,proto3" json:"clientlet,omitempty"`
}

func (x *ClientletCreateCmdResult) Reset() {
	*x = ClientletCreateCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientletCreateCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientletCreateCmdResult) ProtoMessage() {}

func (x *ClientletCreateCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientletCreateCmdResult.ProtoReflect.Descriptor instead.
func (*ClientletCreateCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{10}
}

func (x *ClientletCreateCmdResult) GetClientlet() *Clientlet {
	if x != nil {
		return x.Clientlet
	}
	return nil
}

type ClientletOpCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Op   string `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
}

func (x *ClientletOpCmd) Reset() {
	*x = ClientletOpCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientletOpCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientletOpCmd) ProtoMessage() {}

func (x *ClientletOpCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientletOpCmd.ProtoReflect.Descriptor instead.
func (*ClientletOpCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{11}
}

func (x *ClientletOpCmd) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ClientletOpCmd) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

type ClientletOpCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *OperationResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ClientletOpCmdResult) Reset() {
	*x = ClientletOpCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientletOpCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientletOpCmdResult) ProtoMessage() {}

func (x *ClientletOpCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientletOpCmdResult.ProtoReflect.Descriptor instead.
func (*ClientletOpCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{12}
}

func (x *ClientletOpCmdResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ConnectCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServerletAddress string `protobuf:"bytes,2,opt,name=serverletAddress,proto3" json:"serverletAddress,omitempty"`
	HubUUID          string `protobuf:"bytes,3,opt,name=hubUUID,proto3" json:"hubUUID,omitempty"`
	Broker           string `protobuf:"bytes,5,opt,name=broker,proto3" json:"broker,omitempty"`
	Port             int32  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	BrokerUUID       string `protobuf:"bytes,8,opt,name=brokerUUID,proto3" json:"brokerUUID,omitempty"`
}

func (x *ConnectCmd) Reset() {
	*x = ConnectCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectCmd) ProtoMessage() {}

func (x *ConnectCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectCmd.ProtoReflect.Descriptor instead.
func (*ConnectCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{13}
}

func (x *ConnectCmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectCmd) GetServerletAddress() string {
	if x != nil {
		return x.ServerletAddress
	}
	return ""
}

func (x *ConnectCmd) GetHubUUID() string {
	if x != nil {
		return x.HubUUID
	}
	return ""
}

func (x *ConnectCmd) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *ConnectCmd) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectCmd) GetBrokerUUID() string {
	if x != nil {
		return x.BrokerUUID
	}
	return ""
}

type ConnectCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientlet *Clientlet `protobuf:"bytes,1,opt,name=clientlet,proto3" json:"clientlet,omitempty"`
}

func (x *ConnectCmdResult) Reset() {
	*x = ConnectCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectCmdResult) ProtoMessage() {}

func (x *ConnectCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectCmdResult.ProtoReflect.Descriptor instead.
func (*ConnectCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{14}
}

func (x *ConnectCmdResult) GetClientlet() *Clientlet {
	if x != nil {
		return x.Clientlet
	}
	return nil
}

type ExposeCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port       int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Broker     string `protobuf:"bytes,5,opt,name=broker,proto3" json:"broker,omitempty"`
	BrokerUUID string `protobuf:"bytes,8,opt,name=brokerUUID,proto3" json:"brokerUUID,omitempty"`
}

func (x *ExposeCmd) Reset() {
	*x = ExposeCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExposeCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeCmd) ProtoMessage() {}

func (x *ExposeCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeCmd.ProtoReflect.Descriptor instead.
func (*ExposeCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{15}
}

func (x *ExposeCmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExposeCmd) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ExposeCmd) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *ExposeCmd) GetBrokerUUID() string {
	if x != nil {
		return x.BrokerUUID
	}
	return ""
}

type ExposeCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serverlet *Serverlet `protobuf:"bytes,1,opt,name=serverlet,proto3" json:"serverlet,omitempty"`
}

func (x *ExposeCmdResult) Reset() {
	*x = ExposeCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExposeCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeCmdResult) ProtoMessage() {}

func (x *ExposeCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeCmdResult.ProtoReflect.Descriptor instead.
func (*ExposeCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{16}
}

func (x *ExposeCmdResult) GetServerlet() *Serverlet {
	if x != nil {
		return x.Serverlet
	}
	return nil
}

type HubCreateCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Broker        string `protobuf:"bytes,3,opt,name=broker,proto3" json:"broker,omitempty"`
	Desc          string `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Persist       bool   `protobuf:"varint,7,opt,name=persist,proto3" json:"persist,omitempty"`
	BrokerUUID    string `protobuf:"bytes,8,opt,name=brokerUUID,proto3" json:"brokerUUID,omitempty"`
	Disabled      bool   `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ManualStartup bool   `protobuf:"varint,10,opt,name=manualStartup,proto3" json:"manualStartup,omitempty"`
}

func (x *HubCreateCmd) Reset() {
	*x = HubCreateCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubCreateCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubCreateCmd) ProtoMessage() {}

func (x *HubCreateCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubCreateCmd.ProtoReflect.Descriptor instead.
func (*HubCreateCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{17}
}

func (x *HubCreateCmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HubCreateCmd) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *HubCreateCmd) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *HubCreateCmd) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *HubCreateCmd) GetBrokerUUID() string {
	if x != nil {
		return x.BrokerUUID
	}
	return ""
}

func (x *HubCreateCmd) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *HubCreateCmd) GetManualStartup() bool {
	if x != nil {
		return x.ManualStartup
	}
	return false
}

type HubCreateCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hub *Hub `protobuf:"bytes,1,opt,name=hub,proto3" json:"hub,omitempty"`
}

func (x *HubCreateCmdResult) Reset() {
	*x = HubCreateCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubCreateCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubCreateCmdResult) ProtoMessage() {}

func (x *HubCreateCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubCreateCmdResult.ProtoReflect.Descriptor instead.
func (*HubCreateCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{18}
}

func (x *HubCreateCmdResult) GetHub() *Hub {
	if x != nil {
		return x.Hub
	}
	return nil
}

type HubListCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter          string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	IncludeChildren bool   `protobuf:"varint,3,opt,name=includeChildren,proto3" json:"includeChildren,omitempty"`
}

func (x *HubListCmd) Reset() {
	*x = HubListCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubListCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubListCmd) ProtoMessage() {}

func (x *HubListCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubListCmd.ProtoReflect.Descriptor instead.
func (*HubListCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{19}
}

func (x *HubListCmd) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *HubListCmd) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

type HubListCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hubs []*Hub `protobuf:"bytes,1,rep,name=hubs,proto3" json:"hubs,omitempty"`
}

func (x *HubListCmdResult) Reset() {
	*x = HubListCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubListCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubListCmdResult) ProtoMessage() {}

func (x *HubListCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubListCmdResult.ProtoReflect.Descriptor instead.
func (*HubListCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{20}
}

func (x *HubListCmdResult) GetHubs() []*Hub {
	if x != nil {
		return x.Hubs
	}
	return nil
}

type ServerletCreateCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	HubUUID       string `protobuf:"bytes,3,opt,name=hubUUID,proto3" json:"hubUUID,omitempty"`
	Broker        string `protobuf:"bytes,5,opt,name=broker,proto3" json:"broker,omitempty"`
	Persist       bool   `protobuf:"varint,7,opt,name=persist,proto3" json:"persist,omitempty"`
	BrokerUUID    string `protobuf:"bytes,8,opt,name=brokerUUID,proto3" json:"brokerUUID,omitempty"`
	Disabled      bool   `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	ManualStartup bool   `protobuf:"varint,10,opt,name=manualStartup,proto3" json:"manualStartup,omitempty"`
	Desc          string `protobuf:"bytes,12,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *ServerletCreateCmd) Reset() {
	*x = ServerletCreateCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerletCreateCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerletCreateCmd) ProtoMessage() {}

func (x *ServerletCreateCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerletCreateCmd.ProtoReflect.Descriptor instead.
func (*ServerletCreateCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{21}
}

func (x *ServerletCreateCmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerletCreateCmd) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerletCreateCmd) GetHubUUID() string {
	if x != nil {
		return x.HubUUID
	}
	return ""
}

func (x *ServerletCreateCmd) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *ServerletCreateCmd) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *ServerletCreateCmd) GetBrokerUUID() string {
	if x != nil {
		return x.BrokerUUID
	}
	return ""
}

func (x *ServerletCreateCmd) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ServerletCreateCmd) GetManualStartup() bool {
	if x != nil {
		return x.ManualStartup
	}
	return false
}

func (x *ServerletCreateCmd) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ServerletCreateCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serverlet *Serverlet `protobuf:"bytes,1,opt,name=serverlet,proto3" json:"serverlet,omitempty"`
}

func (x *ServerletCreateCmdResult) Reset() {
	*x = ServerletCreateCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerletCreateCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerletCreateCmdResult) ProtoMessage() {}

func (x *ServerletCreateCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerletCreateCmdResult.ProtoReflect.Descriptor instead.
func (*ServerletCreateCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{22}
}

func (x *ServerletCreateCmdResult) GetServerlet() *Serverlet {
	if x != nil {
		return x.Serverlet
	}
	return nil
}

type ServerletOpCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Op   string `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
}

func (x *ServerletOpCmd) Reset() {
	*x = ServerletOpCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerletOpCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerletOpCmd) ProtoMessage() {}

func (x *ServerletOpCmd) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerletOpCmd.ProtoReflect.Descriptor instead.
func (*ServerletOpCmd) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{23}
}

func (x *ServerletOpCmd) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ServerletOpCmd) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

type ServerletOpCmdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *OperationResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ServerletOpCmdResult) Reset() {
	*x = ServerletOpCmdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wo_proto3_22483931_tmp_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerletOpCmdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerletOpCmdResult) ProtoMessage() {}

func (x *ServerletOpCmdResult) ProtoReflect() protoreflect.Message {
	mi := &file_wo_proto3_22483931_tmp_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerletOpCmdResult.ProtoReflect.Descriptor instead.
func (*ServerletOpCmdResult) Descriptor() ([]byte, []int) {
	return file_wo_proto3_22483931_tmp_rawDescGZIP(), []int{24}
}

func (x *ServerletOpCmdResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_wo_proto3_22483931_tmp protoreflect.FileDescriptor

var file_wo_proto3_22483931_tmp_rawDesc = []byte{
	0x0a, 0x16, 0x77, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x2d, 0x32, 0x32, 0x34, 0x38,
	0x33, 0x39, 0x33, 0x31, 0x2e, 0x74, 0x6d, 0x70, 0x12, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61,
	0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x02, 0x0a, 0x09, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x75,
	0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0xb9, 0x02, 0x0a,
	0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x6c, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x75, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6d, 0x61, 0x6e,
	0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x6e, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63,
	0x6f, 0x6e, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0xf7, 0x01, 0x0a, 0x03, 0x48, 0x75, 0x62,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x38, 0x0a, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x6c, 0x65, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x6c, 0x65, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x6c, 0x65, 0x74, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d,
	0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x75, 0x70, 0x22, 0xb4, 0x01, 0x0a, 0x06, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0xf4, 0x01, 0x0a, 0x0f, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x4e, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18,
	0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2e,
	0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x1a, 0x3d, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xdf, 0x01, 0x0a, 0x0f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6b,
	0x69, 0x70, 0x74, 0x65, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6b,
	0x69, 0x70, 0x74, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x22, 0x46, 0x0a, 0x15, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x52, 0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x0d, 0x42, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x22, 0x46, 0x0a, 0x13, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x52, 0x07, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x22, 0xaa, 0x02, 0x0a, 0x12,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73,
	0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x52, 0x0a, 0x18, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x6c, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x64, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61,
	0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65,
	0x74, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x0e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x4f, 0x70, 0x43, 0x6d, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6f, 0x70, 0x22, 0x4e, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x4f,
	0x70, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0xb2, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x6d,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x22, 0x4a, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6c, 0x65, 0x74, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x6c, 0x65, 0x74, 0x22, 0x6b, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x43, 0x6d, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44,
	0x22, 0x49, 0x0a, 0x0f, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b,
	0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74,
	0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x22, 0xca, 0x01, 0x0a, 0x0c,
	0x48, 0x75, 0x62, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70,
	0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x75, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x22, 0x3a, 0x0a, 0x12, 0x48, 0x75, 0x62, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24,
	0x0a, 0x03, 0x68, 0x75, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x48, 0x75, 0x62, 0x52,
	0x03, 0x68, 0x75, 0x62, 0x22, 0x4e, 0x0a, 0x0a, 0x48, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6d, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x43, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x22, 0x3a, 0x0a, 0x10, 0x48, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x68, 0x75, 0x62, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b,
	0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2e, 0x48, 0x75, 0x62, 0x52, 0x04, 0x68, 0x75, 0x62, 0x73,
	0x22, 0xfe, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x68, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x22, 0x52, 0x0a, 0x18, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75, 0x6e, 0x65, 0x74,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x6c, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c,
	0x65, 0x74, 0x4f, 0x70, 0x43, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x4e, 0x0a, 0x14, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x74, 0x4f, 0x70, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61, 0x6b, 0x2e, 0x69, 0x75,
	0x6e, 0x65, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x61,
	0x6b, 0x2f, 0x77, 0x6f, 0x6e, 0x65, 0x74, 0x2f, 0x69, 0x75, 0x6e, 0x65, 0x74, 0x2f, 0x61, 0x70,
	0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wo_proto3_22483931_tmp_rawDescOnce sync.Once
	file_wo_proto3_22483931_tmp_rawDescData = file_wo_proto3_22483931_tmp_rawDesc
)

func file_wo_proto3_22483931_tmp_rawDescGZIP() []byte {
	file_wo_proto3_22483931_tmp_rawDescOnce.Do(func() {
		file_wo_proto3_22483931_tmp_rawDescData = protoimpl.X.CompressGZIP(file_wo_proto3_22483931_tmp_rawDescData)
	})
	return file_wo_proto3_22483931_tmp_rawDescData
}

var file_wo_proto3_22483931_tmp_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_wo_proto3_22483931_tmp_goTypes = []interface{}{
	(*Serverlet)(nil),                // 0: mainvec.iunet.Serverlet
	(*Clientlet)(nil),                // 1: mainvec.iunet.Clientlet
	(*Hub)(nil),                      // 2: mainvec.iunet.Hub
	(*Broker)(nil),                   // 3: mainvec.iunet.Broker
	(*OperationResult)(nil),          // 4: mainvec.iunet.OperationResult
	(*BrokerCreateCmd)(nil),          // 5: mainvec.iunet.BrokerCreateCmd
	(*BrokerCreateCmdResult)(nil),    // 6: mainvec.iunet.BrokerCreateCmdResult
	(*BrokerListCmd)(nil),            // 7: mainvec.iunet.BrokerListCmd
	(*BrokerListCmdResult)(nil),      // 8: mainvec.iunet.BrokerListCmdResult
	(*ClientletCreateCmd)(nil),       // 9: mainvec.iunet.ClientletCreateCmd
	(*ClientletCreateCmdResult)(nil), // 10: mainvec.iunet.ClientletCreateCmdResult
	(*ClientletOpCmd)(nil),           // 11: mainvec.iunet.ClientletOpCmd
	(*ClientletOpCmdResult)(nil),     // 12: mainvec.iunet.ClientletOpCmdResult
	(*ConnectCmd)(nil),               // 13: mainvec.iunet.ConnectCmd
	(*ConnectCmdResult)(nil),         // 14: mainvec.iunet.ConnectCmdResult
	(*ExposeCmd)(nil),                // 15: mainvec.iunet.ExposeCmd
	(*ExposeCmdResult)(nil),          // 16: mainvec.iunet.ExposeCmdResult
	(*HubCreateCmd)(nil),             // 17: mainvec.iunet.HubCreateCmd
	(*HubCreateCmdResult)(nil),       // 18: mainvec.iunet.HubCreateCmdResult
	(*HubListCmd)(nil),               // 19: mainvec.iunet.HubListCmd
	(*HubListCmdResult)(nil),         // 20: mainvec.iunet.HubListCmdResult
	(*ServerletCreateCmd)(nil),       // 21: mainvec.iunet.ServerletCreateCmd
	(*ServerletCreateCmdResult)(nil), // 22: mainvec.iunet.ServerletCreateCmdResult
	(*ServerletOpCmd)(nil),           // 23: mainvec.iunet.ServerletOpCmd
	(*ServerletOpCmdResult)(nil),     // 24: mainvec.iunet.ServerletOpCmdResult
	nil,                              // 25: mainvec.iunet.OperationResult.AdditionalEntry
}
var file_wo_proto3_22483931_tmp_depIdxs = []int32{
	0,  // 0: mainvec.iunet.Hub.serverlets:type_name -> mainvec.iunet.Serverlet
	1,  // 1: mainvec.iunet.Hub.clientlets:type_name -> mainvec.iunet.Clientlet
	25, // 2: mainvec.iunet.OperationResult.additional:type_name -> mainvec.iunet.OperationResult.AdditionalEntry
	3,  // 3: mainvec.iunet.BrokerCreateCmdResult.broker:type_name -> mainvec.iunet.Broker
	3,  // 4: mainvec.iunet.BrokerListCmdResult.brokers:type_name -> mainvec.iunet.Broker
	1,  // 5: mainvec.iunet.ClientletCreateCmdResult.clientlet:type_name -> mainvec.iunet.Clientlet
	4,  // 6: mainvec.iunet.ClientletOpCmdResult.result:type_name -> mainvec.iunet.OperationResult
	1,  // 7: mainvec.iunet.ConnectCmdResult.clientlet:type_name -> mainvec.iunet.Clientlet
	0,  // 8: mainvec.iunet.ExposeCmdResult.serverlet:type_name -> mainvec.iunet.Serverlet
	2,  // 9: mainvec.iunet.HubCreateCmdResult.hub:type_name -> mainvec.iunet.Hub
	2,  // 10: mainvec.iunet.HubListCmdResult.hubs:type_name -> mainvec.iunet.Hub
	0,  // 11: mainvec.iunet.ServerletCreateCmdResult.serverlet:type_name -> mainvec.iunet.Serverlet
	4,  // 12: mainvec.iunet.ServerletOpCmdResult.result:type_name -> mainvec.iunet.OperationResult
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_wo_proto3_22483931_tmp_init() }
func file_wo_proto3_22483931_tmp_init() {
	if File_wo_proto3_22483931_tmp != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wo_proto3_22483931_tmp_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Serverlet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clientlet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Broker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerCreateCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerCreateCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerListCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerListCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientletCreateCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientletCreateCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientletOpCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientletOpCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExposeCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExposeCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HubCreateCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HubCreateCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HubListCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HubListCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerletCreateCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerletCreateCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerletOpCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wo_proto3_22483931_tmp_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerletOpCmdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wo_proto3_22483931_tmp_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wo_proto3_22483931_tmp_goTypes,
		DependencyIndexes: file_wo_proto3_22483931_tmp_depIdxs,
		MessageInfos:      file_wo_proto3_22483931_tmp_msgTypes,
	}.Build()
	File_wo_proto3_22483931_tmp = out.File
	file_wo_proto3_22483931_tmp_rawDesc = nil
	file_wo_proto3_22483931_tmp_goTypes = nil
	file_wo_proto3_22483931_tmp_depIdxs = nil
}
