// CommandsRunner code generated by toolkit. Should not modify
// implement the runners in _runners.go or _impl.go
package mvp

import (
	api "github.com/mainvec/mvep/toolkit/mvpapi/api"
)

// GetCommandRunner returns the command runner
func GetCommandRunner() *api.PkgCommandRunner {
	return &api.PkgCommandRunner{
		RunGenerateCmd:   runGenerateCmd,
		RunInitializeCmd: runInitializeCmd,
		RunValidateCmd:   runValidateCmd,
	}
}
