// Default implementation generated by toolkit.
// Can be modifid but might be re-genrated by toolkit, if allowed to
package mvep

import (
	"context"
	"errors"

	api "github.com/mainvec/mvep/toolkit/mvepapi/api"
)

func runGenerateCmd(ctx context.Context, cmd *api.GenerateCmd) (*api.GenerateCmdResult, error) {
	return nil, errors.New("command not implemented")
}
func runInitializeCmd(ctx context.Context, cmd *api.InitializeCmd) (*api.InitializeCmdResult, error) {
	return nil, errors.New("command not implemented")
}
func runValidateCmd(ctx context.Context, cmd *api.ValidateCmd) (*api.ValidateCmdResult, error) {
	return nil, errors.New("command not implemented")
}
